### ISSUE TITLE
Add an option for ignoring .gitignore

### ISSUE THREAD

**Issue by kristian** [ranyitz/globitor#2]
Hey @ranyitz, I really like the interactive design of your package! It would be super helpful to me, however I try to glob files which are in my .gitignore. It would be super helpfull to have an option to NOT gitignore things like:

```
npx globitor --no-gitignore
```

... or similar. What do you think? Thanks!

**Comment by ranyitz** [comment]
@kristian thanks! That's a great idea. Would you like to contribute a PR with this change?

Just to make it clearer to contribute i'll add the places that require a change:
1. Addition of the flag to the [CLI app](https://github.com/ranyitz/globitor/blob/7acb9a32dc54b5d9e36feae5cfa26d295cc19965/src/cli.ts#L14)
2. Adjust the [--help](https://github.com/ranyitz/globitor/blob/7acb9a32dc54b5d9e36feae5cfa26d295cc19965/src/cli.ts#L40)
3. Passing of the flag from the cli to [this call](https://github.com/ranyitz/globitor/blob/7acb9a32dc54b5d9e36feae5cfa26d295cc19965/src/getFiles.ts#L8)

**Comment by kristian** [comment]
I never worked much with typescript before, so please have a look before merging. Hope the change is fine, if not let me know!

**Comment by ranyitz** [comment]
Sure, I reviewed the PR, let's continue the discussion there

**Comment by kristian** [comment]
Thanks @ranyitz. Are you going to release it also to NPM? That'd be hepful! Thanks & have a good one!
